---
title: 'Let''s Make Your R Code FastR: Part1'
author: "Nikola Surjanovic"
date: "Simon Fraser University"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- From https://stackoverflow.com/questions/42690955/how-to-insert-footnotes-in-ioslides-presentations-using-rmarkdown, Martin Schmelzer -->
<style>
div.footnotes {
  position: absolute;
  bottom: 0;
  margin-bottom: 10px;
  width: 80%;
  font-size: 0.6em;
}
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script>
  $(document).ready(function() {
    $('slide:not(.backdrop):not(.title-slide)').append('<div class=\"footnotes\">');

    $('footnote').each(function(index) {
      var text  = $(this).html();
      var fnNum = (index+1).toString().sup();
      $(this).html(text + fnNum);

      var footnote   = fnNum + ': ' + $(this).attr('content') + '<br/>';
      var oldContent = $(this).parents('slide').children('div.footnotes').html();
      var newContent = oldContent + footnote;
      $(this).parents('slide').children('div.footnotes').html(newContent);
    });
  });
</script>


# Introductions
## Introductions
### About Me
First-year Master's student studying Statistics  

Research interests: machine learning, goodness-of-fit

### How About You?



## Why Are We Here?
How experienced are you with R? 

What would you like to learn today?  

 - This is "Part 1", but we can cover more (or less)




# Why is R "slow"?
## Why is R "slow"?
[Insert funny picture here.]



## Why is R "slow"?
Often, R is "fast enough"

<footnote content="Hadley Wickham, Advanced R book, http://adv-r.had.co.nz/"> "The overriding concern for R-core is not to make R fast, but to build a stable platform for data analysis and statistics."</footnote>



## Language vs. Implementation
Difference between language and implementation

Alternatives: pqR, Renjin, FastR, etc.




# Timing Your R Code
## Timing Your R Code
Bottlenecks need to be identified

Don't waste time optimizing code that is already fast enough




## Profiling / Timing Code
Depending on the circumstances, we can use one of:

- <b>profvis()</b>
- <b>bench::mark()</b>
- microbenchmark()
- system.time()
- utils::Rprof()
- utils::summaryRprof()


